nodeLinker: node-modules

httpProxy: http://127.0.0.1:7890
httpsProxy: https://127.0.0.1:7890

# npmRegistryServer: "https://registry.npmmirror.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
